config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'groups/index'
  root 'themes#index'
  resources :themes, only: [:new, :create, :show] do
    collection do
      match 'search' => 'themes#search', via: [:get, :post]
    end
    resources :comments, only: [:new, :create] do
      resources :likes, only: [:create, :destroy]
    end
  end
  resources :groups, only: [:index, :new, :create, :show, :edit, :update] do
    resources :messages, only: [:index, :create]
  end

  resources :users, only: :index do
    collection do
      get :likes
    end
  end

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :content, presence: true
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
    @users = current_user.likes
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_message.html.haml
.main-content{data: {message: {id: message.id}}}
  .main-content__header
    %p.main-content__header__name
      = message.user.name
    %p.main-content__header__date
      = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
  %p.main-content__message
    = message.content

app/views/messages/index.html.haml
- breadcrumb :users_groups
-# 下記を記述した箇所にパンくずリストが表示される。
= breadcrumbs separator: " &rsaquo; ", class: 'breadcrumbs'
.wrapper
  .chat-side
    .side-header
      .side-header__header
        お題
      .top-items
        - @users.each do |like|
          .top-items__theme
            = like.theme.title
    .groups
      .groups-header
        グループ
      - current_user.groups.each do |group|
        = link_to group_messages_path(group), class: "group-list__btn" do
          .group-list
            .group-list__name
              = group.name
            .group-list__message
              = group.show_last_message
  .main-chat
    .group-header
      .group-header__info-left
        %p.group-header__name
          = @group.name
        %ul.group-header__menbers
          %p.group-header__menbers__title Menber :
          - @group.users.each do |user|
            %li.group-header__menbers__menber
              = user.name
      .group-header__info-right
        = link_to edit_group_path(@group), class: "group-header__edit" do
          %p.group-header__edit-btn Edit

    .group-messages
      = render @messages
    .form
      = form_for [@group, @message] do |f|
        .new-message
          .input-box
            = f.text_field :content, class: 'input-box__text', placeholder: 'type a message'
          = f.submit 'Send', class: 'input-btn'