config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'groups/index'
  root 'themes#index'
  resources :themes, only: [:new, :create, :show] do
    collection do
      match 'search' => 'themes#search', via: [:get, :post]
    end
    resources :comments, only: [:new, :create] do
      resources :likes, only: [:create, :destroy]
    end
  end
  resources :groups, only: [:index, :new, :create, :show, :edit, :update] do
    resources :messages, only: [:index, :create]
  end

  resources :users, only: :index do
    collection do
      get :likes
    end
  end

end

app/models/theme.rb
class Theme < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes
  validates :title, presence: true, unless: :image?

  mount_uploader :image, ImageUploader
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController

  def index
    @themes = Theme.all.page(params[:page]).order("created_at DESC").per(10)
    @themes_rank = Theme.find(Comment.group(:theme_id).order('count(theme_id) desc').pluck(:theme_id))
  end

  def new
    @theme = Theme.new
  end

  def create
    Theme.create(theme_params)
    redirect_to root_path
  end

  def show
    @theme = Theme.find(params[:id])
    @comments = @theme.comments.includes(:user)
    @comment = Comment.new
    @all_ranks = Comment.find(Like.group(:comment_id).order('count(comment_id) desc').pluck(:comment_id))
    @theme_ranks = @all_ranks.select{ |comment| comment.theme_id == @theme.id }
  end


  def search
    @themes_rank = Theme.find(Comment.group(:theme_id).order('count(theme_id) desc').pluck(:theme_id))
    @themes = Theme.all.page(params[:page]).order("created_at desc").per(10)
    @all_ranks = Comment.find(Like.group(:comment_id).order('count(comment_id) desc').pluck(:comment_id))
  end




  private
  def theme_params
    params.require(:theme).permit(:title, :image).merge(user_id: current_user.id)
  end

  def search_params
    params.require(:q).permit(:sorts)
    # 他のパラメーターもここに入れる
  end

end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/themes/index.html.haml
.group-content
  .title お題
  .sorting
    = link_to '新着順', root_path, class: 'turn sorting__theme', value: 'arrival'
    = link_to 'コメント数順', search_themes_path, class: 'turn sorting__image'
  .contents
    - @themes.each do |theme|
      = link_to theme_path(theme), class: 'content__theme__title' do
        .content
          .content__theme 
            = theme.title
            = image_tag theme.image.url, class: 'content__theme__title__image' if theme.image.present?
          .content__comment
            .content__comment__title
              コメント数:
            .content__comment__number
              = theme.comments.count
  = paginate(@themes)



  

app/views/themes/new.html.haml
- breadcrumb :users_new_theme
-# 下記を記述した箇所にパンくずリストが表示される。
= breadcrumbs separator: " &rsaquo; "
.group-content
  .new-content
    .title お題の作成
    .new-content__theme
      = form_for  @theme do |f|
        = f.text_area :title, placeholder: "お題&#13;&#10;35文字まで".html_safe , cols: "30", rows: "6", class: 'new-content__theme__text',maxlength: '35'
        = f.file_field :image, class: 'new-content__theme__image'
        .note ※どちらか入力してください
        = f.submit value: '投稿', class: 'new-content__theme__submit'

app/views/themes/search.html.haml
.group-content
  .title お題
  .sorting
    = link_to '新着順', root_path, class: 'turn sorting__theme', value: 'arrival'
    = link_to 'コメント数順', search_themes_path, class: 'turn sorting__image'
  .contents
    - @themes_rank.each do |theme|
      .content
        .content__theme 
          = link_to theme_path(theme), class: 'content__theme__title' do
            = theme.title
            = image_tag theme.image.url, class: 'content__theme__title__image' if theme.image.present?
        .content__comment
          .content__comment__title
            コメント数:
          .content__comment__number
            = theme.comments.count
    - @themes.each do |theme|
      = link_to theme_path(theme), class: 'content__theme__title' do
        - unless theme.comments.present?
          .content
            .content__theme 
              = theme.title
              = image_tag theme.image.url, class: 'content__theme__title__image' if theme.image.present?
            .content__comment
              .content__comment__title
                コメント数:
              .content__comment__number
                = theme.comments.count

app/views/themes/show.html.haml
- breadcrumb :themes
-# 下記を記述した箇所にパンくずリストが表示される。
= breadcrumbs separator: " &rsaquo; ", class: 'breadcrumbs'
.group-content
  .show-content
    .show-content__theme
      = @theme.title
      = image_tag @theme.image.url, class: 'show-content__theme__image' if @theme.image.present?
    .show-content__ranks
      - @theme_ranks.each.with_index(1) do |comment, i|
        - if i < 4
          %div(class="rank rank__#{i}")
            = i
            位
          %div(class="comment comment__#{i}")
            .comment__left
              = markdown(comment.text).html_safe
            .comment__right
              %div(class="comment__right__#{i}")
                = comment.likes.count
              %div(class="comment__right__name#{i}")
                = comment.user.name
      - unless @theme_ranks.present?
        .show-content__ranks__none
          ※いいね数のランキングが表示されます
          %br
          ランキング入りを目指して頑張ろう！！
    .show-content__comments
      - @comments.each do |comment|
        .comment
          .comment__left
            = markdown(comment.text).html_safe
          .comment__right
            %div{ id: "like-btn-#{comment.id}" }
              = render partial: "likes/like", locals: { comment: comment}
            .comment__right__name
              = comment.user.name
      - unless @comments.present?
        .show-content__comments__none 
          ※まだコメントがありません
          %br 
          コメントを入力してみよう！！
      
    = form_for [@theme, @comment], id: "new_comment" do |f|
      .new-content__form
        = f.text_area :text, placeholder: 'コメント', class: 'new-content__theme__text', id: 'editor'
        %link{:href => "https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css", :rel => "stylesheet"}/
        %script{:src => "https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"}
        :javascript
          var simplemde = new SimpleMDE({ element: document.getElementById("editor") });
        = f.submit value: '投稿', class: 'new-content__form__submit'