config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'groups/index'
  root 'themes#index'
  resources :themes, only: [:new, :create, :show] do
    collection do
      match 'search' => 'themes#search', via: [:get, :post]
    end
    resources :comments, only: [:new, :create] do
      resources :likes, only: [:create, :destroy]
    end
  end
  resources :groups, only: [:index, :new, :create, :show, :edit, :update] do
    resources :messages, only: [:index, :create]
  end

  resources :users, only: :index do
    collection do
      get :likes
    end
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :comment
  belongs_to :theme
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like

  def create
    @like = Like.create(comment_id: params[:comment_id], user_id: current_user.id, theme_id: params[:theme_id])
    @theme = Theme.find(params[:theme_id])
    # redirect_to theme_path(@theme)
    # redirect_to root_path
  end

  def destroy
    @like = Like.find_by(comment_id: params[:comment_id], user_id: current_user.id)
    @theme = Theme.find(params[:theme_id])
    @like.destroy
    # redirect_to theme_path(@theme)
    # redirect_to root_path
  end

  private
  def set_like
    @comment = Comment.find(params[:comment_id])
    @theme = Theme.find(params[:theme_id])
  end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.haml
-if Like.find_by(user_id: current_user.id, theme_id: @theme.id, comment_id: comment.id)
  = link_to theme_comment_like_path(@theme, comment, current_user), method: :delete, remote: true, id: :"like-button-#{comment.id}", class: 'destroy-icon' do
    = icon('fas', 'heart')
    = comment.likes.count
-else
  = link_to theme_comment_likes_path(@theme, comment), method: :post, remote: true, id: :"like-button-#{comment.id}", class: 'create-icon'  do
    = icon('fas', 'heart')
    = comment.likes.count

app/views/likes/create.js.haml
$("#like-btn-#{@comment.id}").html("#{j(render partial: "like", locals: { comment: @comment } )}");

app/views/likes/destroy.js.haml
$("#like-btn-#{@comment.id}").html("#{j(render partial: "like", locals: { comment: @comment } )}");