config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'groups/index'
  root 'themes#index'
  resources :themes, only: [:new, :create, :show] do
    collection do
      match 'search' => 'themes#search', via: [:get, :post]
    end
    resources :comments, only: [:new, :create] do
      resources :likes, only: [:create, :destroy]
    end
  end
  resources :groups, only: [:index, :new, :create, :show, :edit, :update] do
    resources :messages, only: [:index, :create]
  end

  resources :users, only: :index do
    collection do
      get :likes
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :themes
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :comments
  has_many :likes
  has_many :messages


  validates :name, presence: true, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @all_ranks = Comment.find(Like.group(:comment_id).order('count(comment_id) desc').pluck(:comment_id))
    @my_ranks = @all_ranks.select{ |comment| comment.user_id == current_user.id }
    # respond_to do |format|
    #   format.html
    #   format.json
    # end
  end

  def likes
    @users = current_user.likes.page(params[:page]).order("created_at ASC").per(10)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.haml
- breadcrumb :users
-# 下記を記述した箇所にパンくずリストが表示される。
= breadcrumbs separator: " &rsaquo; "
.group-content
  .title マイページ
  .my-user-content
    .my-user-content__current_rank
      - likes_count_total = 0
      - @my_ranks.each.with_index(1) do |comment, i|
        - likes_count_total = likes_count_total + comment.likes.count
      - if likes_count_total >= 25
        - rank = "A"
        - current_rank = "現在は#{rank}ランクです"
        - after_rank = "最高ランクです"
      - elsif likes_count_total >= 20
        - rank = "B"
        - current_rank = "現在は#{rank}ランクです"
        - after_rank = "次のランクまで#{25 - likes_count_total}いいね"
      - elsif likes_count_total >= 15
        - rank = "C"
        - current_rank = "現在は#{rank}ランクです"
        - after_rank = "次のランクまで#{20 - likes_count_total}いいね"
      - elsif likes_count_total >= 10
        - rank = "D"
        - current_rank = "現在は#{rank}ランクです"
        - after_rank = "次のランクまで#{15 - likes_count_total}いいね"
      - elsif likes_count_total >= 0
        - rank = "E"
        - current_rank = "現在は#{rank}ランクです"
        - after_rank = "次のランクまで#{10 - likes_count_total}いいね"
      = current_rank
    .my-user-content__after_rank
      = after_rank
    .my-user-content__comprehensive
      .my-user-content__score__total
        総合いいね数：
        = likes_count_total
      .my-user-content__score__average
        平均いいね：
        - likes_count_average = 0
        - likes_count_average = likes_count_total / @my_ranks.count.to_f
        = likes_count_average.round(1)
  .note ※自分のコメントがいいねされるとランクが上がるよ！
  .my-user-btn
    = link_to 'お題作成', new_theme_path, class: 'my-user-btn__btn'
    = link_to 'グループ作成', new_group_path, class: 'my-user-btn__btn'
    = link_to 'いいね一覧', likes_users_path, class: 'my-user-btn__btn'

  .my-user-groups
    .my-user-groups__title
      グループ
    - current_user.groups.each do |group|
      = link_to group_messages_path(group), class: "my-user-groups__url" do
        .my-user-groups__box
          .my-user-groups__box__name
            = group.name
          .my-user-groups__box__number
            - count = 0
            - count = group.users.count
            = "#{count}人"

app/views/users/likes.html.haml
- breadcrumb :users_likes
-# 下記を記述した箇所にパンくずリストが表示される。
= breadcrumbs separator: " &rsaquo; "
.group-content
  .title いいね一覧
  .my-user-likes-contents
    - @users.each do |like|
      .my-user-likes-content
        = link_to theme_path(like.theme), class: 'my-user-likes-content__title' do
          = like.theme.title
          = image_tag like.theme.image.url, class: 'my-user-likes-content__title__image' if like.theme.image.present?
        .my-user-likes-content__comment
          = markdown(like.comment.text).html_safe
  = paginate(@users)